oracle:
  object-storage:
    namespace: ${OCI_NAMESPACE}
    bucketName: ${OCI_BUCKET_NAME}
    region: ${OCI_REGION}
    user: ${OCI_STORAGE_USER}
    fingerprint: ${OCI_STORAGE_FINGERPRINT}
    tenancy: ${OCI_TENANCY}
    key: ${OCI_STORAGE_KEY}
