services:
  app:
    container_name: app-${DEPLOY_ENV:-main}
    image: ${APP_IMAGE:-waps-server:local}
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Database
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # URI
      SERVER_URL: ${SERVER_URL:-http://localhost}
      # Auth
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      KAKAO_REST_API_KEY: ${KAKAO_REST_API_KEY}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      # Oracle Object Storage
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      OCI_STORAGE_USER: ${OCI_STORAGE_USER}
      OCI_STORAGE_FINGERPRINT: ${OCI_STORAGE_FINGERPRINT}
      OCI_STORAGE_KEY: ${OCI_STORAGE_KEY}
      OCI_TENANCY: ${OCI_TENANCY}
      OCI_REGION: ${OCI_REGION}
      OCI_NAMESPACE: ${OCI_NAMESPACE}
      OCI_BUCKET_NAME: ${OCI_BUCKET_NAME}
    networks:
      - waps-network

networks:
  waps-network:
    external: true
