services:
  app:
    container_name: app
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Database
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # URI
      SERVER_URL: ${SERVER_URL}
      # Auth
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      KAKAO_REST_API_KEY: ${KAKAO_REST_API_KEY}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      # Oracle Object Storage
      OCI_USER: ${OCI_USER}
      OCI_FINGERPRINT: ${OCI_FINGERPRINT}
      OCI_KEY: ${OCI_KEY}
      OCI_TENANCY: ${OCI_TENANCY}
      OCI_REGION: ${OCI_REGION}
      OCI_NAMESPACE: ${OCI_NAMESPACE}
      OCI_BUCKET_NAME: ${OCI_BUCKET_NAME}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - waps-network

  caddy:
    container_name: caddy
    image: caddy:2.11.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      SERVER_URL: ${SERVER_URL}
    networks:
      - waps-network
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

networks:
  waps-network:
    external: true

volumes:
  caddy_data:
  caddy_config:
